Add thumbnails to SearchVideo
Hexer10/youtube_explode_dart pull request #73
Opened 2020-09-23 06:44 UTC by shinyford

Hi - I found a need for video thumbnails in the SearchVideo object, similar to the Video object; so added them in a way that suited my needs. Hope this is a useful addition for the main version of youtube_explode_dart.

Great library, BTW - really useful. Thanks!

2020-09-24 15:10 UTC, Hexer10 requested changes
Thanks for the PR! This is implemented correctly, the only thing is that you should remove the flutter_test from the dev dependencies

2020-09-25 11:21 UTC, shinyford commented
Done.

2020-09-26 07:46 UTC, Hexer10 approved these changes

2020-10-17 20:26 UTC, Hexer10 commented
Sorry if this took so long however I was focus on getting the json types done... However this will be in the next version (1.6.1)

2020-10-17 20:26 UTC, merged